### ISSUE TITLE
Slow load time for XTKS

### ISSUE THREAD

**Issue by rsheftel** [quantopian/trading_calendars#155] opened 2020-09-13 23:50 UTC
I noticed that the load time for most all calendars are around 1.5 seconds, except the XTKS calendar which takes 12.2 seconds to load. Is there any particular reason for that?

This is the code and results I used:

```
from datetime import datetime
import trading_calendars as tc

def load_times():
    for name in tc.calendar_utils._default_calendar_factories:
        print(name, end='')
        start = datetime.now()
        _ = mcal.get_calendar(name)
        end = datetime.now()
        print(f': run time is {end - start}')
```

```
ASEX: run time is 0:00:01.462395
BVMF: run time is 0:00:01.608703
CMES: run time is 0:00:01.247221
IEPA: run time is 0:00:01.221055
XAMS: run time is 0:00:01.239995
XASX: run time is 0:00:01.405535
XBKK: run time is 0:00:01.483120
XBOG: run time is 0:00:01.902455
XBOM: run time is 0:00:00.635975
XBRU: run time is 0:00:01.259231
XBUD: run time is 0:00:01.545929
XBUE: run time is 0:00:01.647241
XCBF: run time is 0:00:01.397777
XCSE: run time is 0:00:01.523843
XDUB: run time is 0:00:01.301222
XFRA: run time is 0:00:01.396143
XHEL: run time is 0:00:01.423694
XHKG: run time is 0:00:01.365153
XICE: run time is 0:00:01.561660
XIDX: run time is 0:00:01.219812
XIST: run time is 0:00:01.244760
XJSE: run time is 0:00:01.435470
XKAR: run time is 0:00:01.075075
XKLS: run time is 0:00:01.191726
XKRX: run time is 0:00:00.940299
XLIM: run time is 0:00:01.465012
XLIS: run time is 0:00:01.357335
XLON: run time is 0:00:01.407390
XMAD: run time is 0:00:01.282585
XMEX: run time is 0:00:01.377445
XMIL: run time is 0:00:01.336494
XMOS: run time is 0:00:01.307830
XNYS: run time is 0:00:01.408174
XNZE: run time is 0:00:01.423343
XOSL: run time is 0:00:01.464810
XPAR: run time is 0:00:01.283910
XPHS: run time is 0:00:01.333504
XPRA: run time is 0:00:01.456183
XSES: run time is 0:00:00.961805
XSGO: run time is 0:00:01.739328
XSHG: run time is 0:00:00.709314
XSTO: run time is 0:00:01.572027
XSWX: run time is 0:00:01.435308
XTAI: run time is 0:00:01.137340
XTKS: run time is 0:00:12.211477
XTSE: run time is 0:00:01.481504
XWAR: run time is 0:00:01.544426
XWBO: run time is 0:00:01.442748
us_futures: run time is 0:00:00.859409
24/7: run time is 0:00:01.463259
24/5: run time is 0:00:01.034509
```

**Comment by richafrank** [comment] 2020-09-14 13:56
Hey, thanks @rsheftel . I wasn't able to reproduce this locally. Each of my runs has all but a couple loading in under 1s, and the largest time at ~3s or 1s, but it wasn't consistent which those couple were. Are you able to reproduce this consistently?

FWIW I replaced `mcal` in your code with `tc`. Not sure if `mcal` is doing anything exciting.

**Comment by rsheftel** [comment] 2020-09-14 14:27
Got it. I will investigate over there

**Comment by leonarduschen** [comment] 2020-09-14 17:05
@rsheftel turns out the issue is with `next_non_holiday_weekday` in `tcal.xtks_holidays.py` being computationally expensive. Removing the 2 holidays associated with it reduces the time for `mcal.get_calendar('XTKS')` by a factor of 10.

Perhaps this, combined with how `trading_calendars` and `pandas_market_calendar` handle things slightly differently, causes the slow load time.

Also were you using Python 32-bit? I tried using Python 64-bit and `mcal.get_calendar('XTKS')` is only 2x slower instead of 10x. I don't know why this is the case but maybe it's because `TradingCalendar` uses `np.int64`.

**Comment by rsheftel** [comment] 2020-09-14 20:22
Just for completeness I am using 64-bit Ubuntu

**Comment by gerrymanoim** [comment] 2020-09-22 16:54
Closed by https://github.com/quantopian/trading_calendars/pull/159 (please let me know if that isn't the case).

**Closed** 2020-09-22 16:54 UTC
Labels: pandas_market_calendars
